### ISSUE TITLE
Exception when using Nancy.Serialization.JsonNet after upgrading to Nancy 2.0.0

### ISSUE THREAD

**Issue by qusma** [NancyFx/Nancy.Serialization.JsonNet#72]
### Description
Method 'CanDeserialize' in type 'Nancy.Serialization.JsonNet.JsonNetBodyDeserializer' from assembly 'Nancy.Serialization.JsonNet, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Nancy.Extensions.AssemblyExtensions.SafeGetExportedTypes(Assembly assembly)
   at Nancy.DefaultTypeCatalog.<>c.<GetTypesAssignableTo>b__4_0(Assembly assembly)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Nancy.DefaultTypeCatalog.GetTypesAssignableTo(Type type)
   at Nancy.DefaultTypeCatalog.<>c__DisplayClass3_0.<GetTypesAssignableTo>b__0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Nancy.DefaultTypeCatalog.GetTypesAssignableTo(Type type, TypeResolveStrategy strategy)
   at Nancy.TypeCatalogExtensions.GetTypesAssignableTo[TType](ITypeCatalog typeCatalog)
   at Nancy.Bootstrapper.NancyInternalConfiguration.<>c.<get_Default>b__1_0(ITypeCatalog typeCatalog)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.GetInitializedInternalConfiguration()
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, HostConfiguration configuration, Uri[] baseUris)
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, Uri[] baseUris)

### Steps to Reproduce
Simply launch nancy with the json.net serializer.

### System Configuration
.NET 4.7

- Nancy version: 2.0.0
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by Gouar** [comment]
Hi,
I got the same exception today after upgrading to Nancy 2.0.0. I fixed it by upgrading Nancy.Serialization.JsonNet from 1.4.1 to 2.0.0-clinteastwood (check "Include prerelease").

**Comment by bmhoang** [comment]
I got the same issue
